'use client';

import Sidebar from '../components/Sidebar';
import Header from '../components/Header';

function Reports() {
  const reports = [
    {
      id: 1,
      type: 'Monthly Sales Report',
      date: '2024-01-01',
      generatedBy: 'Admin',
      status: 'Completed',
    },
    {
      id: 2,
      type: 'Driver Performance',
      date: '2024-01-15',
      generatedBy: 'Manager',
      status: 'Completed',
    },
    {
      id: 3,
      type: 'Customer Satisfaction',
      date: '2024-01-20',
      generatedBy: 'Admin',
      status: 'Pending',
    },
    {
      id: 4,
      type: 'Zone Efficiency',
      date: '2024-01-10',
      generatedBy: 'Supervisor',
      status: 'Completed',
    },
    {
      id: 5,
      type: 'Revenue Analysis',
      date: '2024-01-05',
      generatedBy: 'Admin',
      status: 'Completed',
    },
    {
      id: 6,
      type: 'Order Trends',
      date: '2024-01-25',
      generatedBy: 'Manager',
      status: 'In Progress',
    },
  ];

  return (
    <div className="admin-app">
      <Sidebar />

      <div className="content">
        <Header title="Reports" />

        <main className="container-fluid">
          <div className="page-section">
            <div className="card">
              <div className="card-body">

                {/* Top bar */}
                <div className="mb-3">
                  <h5 className="mb-0">Report List</h5>
                </div>

                {/* Table */}
                <div className="table-responsive">
                  <table className="table datatable">
                    <thead className="table-dark">
                      <tr>
                        <th>#</th>
                        <th>Report Type</th>
                        <th>Date</th>
                        <th>Generated By</th>
                        <th>Status</th>
                        <th>Actions</th>
                      </tr>
                    </thead>

                    <tbody>
                      {reports.map((r, index) => (
                        <tr key={r.id}>
                          <td>{index + 1}</td>
                          <td>{r.type}</td>
                          <td>{r.date}</td>
                          <td>{r.generatedBy}</td>
                          <td>{r.status}</td>
                          <td>
                            {r.status === 'Completed' ? (
                              <button className="btn btn-sm btn-primary">
                                Download
                              </button>
                            ) : (
                              <button className="btn btn-sm btn-secondary">
                                Generate
                              </button>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

              </div>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}

export default Reports;
